#ifndef __PERIDOT_I2C_REGS_H__
#define __PERIDOT_I2C_REGS_H__

#include <io.h>

/* I2C access register */
#define PERIDOT_I2C_ACCESS_REG              0
#define IOADDR_PERIDOT_I2C_ACCESS(base) \
  __IO_CALC_ADDRESS_NATIVE(base, PERIDOT_I2C_ACCESS_REG)
#define IORD_PERIDOT_I2C_ACCESS(base) \
  IORD(base, PERIDOT_I2C_ACCESS_REG)
#define IOWR_PERIDOT_I2C_ACCESS(base, data) \
  IOWR(base, PERIDOT_I2C_ACCESS_REG, data)
#define PERIDOT_I2C_ACCESS_RXDATA_MSK       (0xff)
#define PERIDOT_I2C_ACCESS_RXDATA_OFST      (0)
#define PERIDOT_I2C_ACCESS_TXDATA_MSK       (0xff)
#define PERIDOT_I2C_ACCESS_TXDATA_OFST      (0)
#define PERIDOT_I2C_ACCESS_NACK_MSK         (0x100)
#define PERIDOT_I2C_ACCESS_NACK_OFST        (8)
#define PERIDOT_I2C_ACCESS_RDY_MSK          (0x200)
#define PERIDOT_I2C_ACCESS_RDY_OFST         (9)
#define PERIDOT_I2C_ACCESS_STA_MSK          (0x200)
#define PERIDOT_I2C_ACCESS_STA_OFST         (9)
#define PERIDOT_I2C_ACCESS_DIR_MSK          (0x400)
#define PERIDOT_I2C_ACCESS_DIR_OFST         (10)
#define PERIDOT_I2C_ACCESS_PC_MSK           (0x800)
#define PERIDOT_I2C_ACCESS_PC_OFST          (11)
#define PERIDOT_I2C_ACCESS_SC_MSK           (0x1000)
#define PERIDOT_I2C_ACCESS_SC_OFST          (12)
#define PERIDOT_I2C_ACCESS_IRQENA_MSK       (0x8000)
#define PERIDOT_I2C_ACCESS_IRQENA_OFST      (15)

/* I2C config register */
#define PERIDOT_I2C_CONFIG_REG              1
#define IOADDR_PERIDOT_I2C_CONFIG(base) \
  __IO_CALC_ADDRESS_NATIVE(base, PERIDOT_I2C_CONFIG_REG)
#define IORD_PERIDOT_I2C_CONFIG(base)\
  IORD(base, PERIDOT_I2C_CONFIG_REG)
#define IOWR_PERIDOT_I2C_CONFIG(base, data) \
  IOWR(base, PERIDOT_I2C_CONFIG_REG, data)
#define PERIDOT_I2C_CONFIG_CLKDIV_MSK       (0x3ff)
#define PERIDOT_I2C_CONFIG_CLKDIV_OFST      (0)
#define PERIDOT_I2C_CONFIG_RST_MSK          (0x8000)
#define PERIDOT_I2C_CONFIG_RST_OFST         (15)

#endif /* __PERIDOT_I2C_REGS_H__ */
